# Generated by Django 4.2.21 on 2025-08-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_city_state_delete_location_city_state_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
