# Generated by Django 4.2.23 on 2025-08-22 15:23

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User profile avatar image",
                max_length=500,
                null=True,
                upload_to=apps.users.models.user_avatar_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail version of avatar",
                max_length=500,
                null=True,
                upload_to=apps.users.models.user_avatar_upload_path,
            ),
        ),
    ]
